### ISSUE TITLE
/provider_suggestions always returns the same value, regardless of query

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/teacher-training-api#1685]
### What did you do? (steps to reproduce)

Accessed the provider suggestions endpoint at [`/provider_suggestions?query=abc`](https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1/provider_suggestions?query=abc).

### What happened? (actual results)

No matter what the query the same three results are always returned:

```
{
    "data": [{
        "id": "O66",
        "type": "Oxford Brookes University"
    }, {
        "id": "1DE",
        "type": "Oxfordshire Teacher Training"
    }, {
        "id": "O33",
        "type": "Oxford University"
    }],
    "jsonapi": {
        "version": "1.0"
    }
}
```

For example, `ark` or `1ZU` (ARK Teacher Training), returns the same three results.

### What should have happened? (expected results)

This endpoint should return a list that matches the query

**Comment by defong** [comment]
it is captured here https://trello.com/c/DfsCC8OD/635-implement-public-v1-provider-suggestions

https://github.com/DFE-Digital/teacher-training-api/blob/928d6f2bbb2aa38d75cdd65b133062bf4107997c/app%2Fcontrollers%2Fapi%2Fpublic%2Fv1%2Fprovider_suggestions_controller.rb#L9-L21
